import SideMenu from "@/components/layout/SideMenu.tsx/SideMenu";
import { BandBar, LiveScheduleCard } from "@/components/ui/liveScheduleCard";
export default function StageEvent() {
  return (
    <div>
      <SideMenu />
      <h1 className="flex justify-center font-extrabold text-4xl p-5">
        ライブ紹介
      </h1>
      <div className="flex flex-col items-center gap-2 ">
        <LiveScheduleCard stageName="ステージ1">
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="バンド名"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="finished"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="水"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちバンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="finished"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="東タ夕日"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="西田"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="upcoming"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="バンド名"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
        </LiveScheduleCard>
        <LiveScheduleCard stageName="ステージ2">
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="バンド名"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="水"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="東タ夕日"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="西田"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="バンド名"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
        </LiveScheduleCard>{" "}
        <LiveScheduleCard stageName="ステージ3">
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="バンド名"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="水"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="東タ夕日"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="西田"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
          <BandBar
            startTime="10:00"
            endTime="20:00"
            bandName="バンド名"
            thumbnail=""
            description="こんにちは私た州専ンドです。こんにちは私ちは北九州高専バンドです。こんにちはたちは北九州高専バンドで。こんにちは私たちは北九州高専バンドすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすすiawoefjaoefjoawjefoawejfoaweです。こんにちは私たちは北九州高専バンドです。こんにちは私たちは北九州高専バンドです。こんにちは私たち州高専バンドです。"
            state="ongoing"
          />
        </LiveScheduleCard>
      </div>
    </div>
  );
}
